# Generated by Django 5.2.6 on 2026-08-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_committed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
