# Generated by Django 5.2.6 on 2026-08-31 07:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_exchangerate_options'),
        ('orders', '0002_order_stock_committed'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='base_currency',
            field=models.CharField(default='INR', help_text='What the amounts above are in.', max_length=8),
        ),
        migrations.AddField(
            model_name='order',
            name='charged_delivery_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='charged_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='charged_subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='charged_tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='charged_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='destination_country',
            field=models.ForeignKey(blank=True, help_text='Resolved from the shipping address, for tax and reporting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='geo.country'),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), help_text='Units of the charged currency per unit of the base currency.', max_digits=18),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shipping.shippingmethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method_name',
            field=models.CharField(blank=True, help_text='Copied at checkout, so renaming a method later cannot rewrite it.', max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='INR', help_text='What the customer was charged in.', max_length=8),
        ),
    ]
