# Generated by Django 5.2.6 on 2026-08-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('login', 'Sign in'), ('verify', 'Verify an address')], default='login', max_length=10)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'one-time code',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['email', 'purpose', '-created_at'], name='accounts_on_email_bb08c7_idx')],
            },
        ),
    ]
