# Generated by Django 5.2.6 on 2026-08-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberseries',
            name='kind',
            field=models.CharField(choices=[('ORD', 'Order'), ('INV', 'Invoice'), ('PAY', 'Payment'), ('SHP', 'Shipment'), ('RET', 'Return'), ('SUP', 'Support ticket')], max_length=3),
        ),
    ]
