# Generated by Django 5.2.6 on 2026-08-25 09:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage off'), ('fixed', 'Fixed amount off'), ('free_shipping', 'Free shipping')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percent (e.g. 10 = 10%) or a flat amount, per discount type.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for percentage coupons. Blank means uncapped.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valid_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total redemptions allowed. Blank means unlimited.', null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_public', models.BooleanField(default=True, help_text='Show on the storefront offers strip.')),
                ('first_order_only', models.BooleanField(default=False)),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Leave empty to apply to every category.', related_name='coupons', to='catalog.category')),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Leave empty to apply to every product.', related_name='coupons', to='catalog.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
