# Generated by Django 5.2.6 on 2026-08-25 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_available', models.PositiveIntegerField(db_index=True, default=0)),
                ('quantity_reserved', models.PositiveIntegerField(default=0)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('allow_backorder', models.BooleanField(default=False)),
                ('warehouse_location', models.CharField(blank=True, max_length=120)),
                ('restocked_at', models.DateTimeField(blank=True, null=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalog.productvariant')),
            ],
            options={
                'verbose_name_plural': 'inventory',
                'ordering': ('variant__product__name',),
                'indexes': [models.Index(fields=['quantity_available'], name='inventory_available_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('purchase', 'Purchase / restock'), ('sale', 'Sale'), ('reservation', 'Reserved for order'), ('release', 'Reservation released'), ('cancellation', 'Order cancelled'), ('return', 'Customer return'), ('adjustment', 'Manual adjustment'), ('damage', 'Damaged / written off')], db_index=True, max_length=20)),
                ('quantity', models.IntegerField(help_text='Signed: positive adds stock, negative removes it.')),
                ('quantity_after', models.IntegerField(default=0, help_text='Available quantity recorded right after this movement.')),
                ('reference', models.CharField(blank=True, db_index=True, help_text='Order number or PO reference.', max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['variant', '-created_at'], name='movement_variant_time_idx'), models.Index(fields=['reason', '-created_at'], name='movement_reason_time_idx')],
            },
        ),
    ]
