# Generated by Django 5.2.6 on 2026-08-31 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_exchangerate_options'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='quantity_damaged',
            field=models.PositiveIntegerField(default=0, help_text='Written off -- counted out of available stock.'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_returned',
            field=models.PositiveIntegerField(default=0, help_text='Units that came back and were put away again.'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warehouse_location',
            field=models.CharField(blank=True, help_text='Aisle or bin within the warehouse.', max_length=120),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Where new stock lands unless told otherwise.')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers are picked from first.')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='geo.country')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text="Where this variant's stock is held.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='inventory.warehouse'),
        ),
    ]
