# Generated by Django 5.2.6 on 2026-08-25 09:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='flash-sales/')),
            ],
            options={
                'ordering': ('-start_at',),
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional portrait crop.', null=True, upload_to='banners/mobile/')),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('cta_label', models.CharField(blank=True, default='Shop now', max_length=60)),
                ('position', models.CharField(choices=[('hero', 'Homepage hero carousel'), ('strip', 'Promotional strip'), ('sidebar', 'Category sidebar'), ('footer', 'Above footer')], db_index=True, default='hero', max_length=16)),
                ('background_color', models.CharField(blank=True, help_text='e.g. #0f172a', max_length=7)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('click_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ('sort_order', '-created_at'),
                'indexes': [models.Index(fields=['position', 'is_active', 'sort_order'], name='banner_slot_idx')],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('badge_text', models.CharField(blank=True, max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('coupon', models.ForeignKey(blank=True, help_text='Optional -- shows the code and terms on the offer card.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='coupons.coupon')),
            ],
            options={
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='FlashSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity_limit', models.PositiveIntegerField(default=0, help_text='0 means no cap beyond available stock.')),
                ('sold_count', models.PositiveIntegerField(default=0, editable=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketing.flashsale')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale_items', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('flash_sale', 'variant'), name='unique_variant_per_flash_sale')],
            },
        ),
    ]
