# Generated by Django 5.2.6 on 2026-08-31 07:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0002_alter_exchangerate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('carrier', models.CharField(blank=True, max_length=64)),
                ('min_days', models.PositiveSmallIntegerField(default=3, help_text='Fastest realistic delivery, in days.')),
                ('max_days', models.PositiveSmallIntegerField(default=7, help_text='Slowest realistic delivery, in days.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('countries', models.ManyToManyField(blank=True, related_name='shipping_zones', to='geo.country')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_weight_grams', models.PositiveIntegerField(default=0)),
                ('max_weight_grams', models.PositiveIntegerField(blank=True, help_text='Leave empty for no upper limit.', null=True)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='In the base currency.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_order_value', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty for no upper limit.', max_digits=12, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='In the base currency.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('free_over', models.DecimalField(blank=True, decimal_places=2, help_text='Order value at or above which this method ships free.', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingmethod')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingzone')),
            ],
            options={
                'ordering': ['zone', 'method', 'min_weight_grams', 'min_order_value'],
                'indexes': [models.Index(fields=['zone', 'method', 'is_active'], name='shipping_sh_zone_id_d6f388_idx')],
            },
        ),
    ]
