# Generated by Django 5.2.6 on 2026-08-31 07:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_pg_trgm_extension'),
        ('geo', '0002_alter_exchangerate_options'),
        ('orders', '0002_order_stock_committed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Shown on the invoice, e.g. CGST, VAT, GST.', max_length=32)),
                ('percent', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('applies_when', models.CharField(choices=[('any', 'Always'), ('intra', "Only within the seller's state"), ('inter', "Only outside the seller's state")], default='any', help_text="India splits GST by destination: CGST and SGST within the seller's state, IGST outside it.", max_length=8)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, help_text='Leave empty while the rule is current.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(blank=True, help_text='Leave empty to apply to every product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='catalog.category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='geo.country')),
                ('state', models.ForeignKey(blank=True, help_text='Leave empty to apply to the whole country.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='geo.state')),
            ],
            options={
                'ordering': ['country__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderTaxLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('percent', models.DecimalField(decimal_places=3, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, help_text="In the order's base currency.", max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_lines', to='orders.order')),
                ('rule', models.ForeignKey(blank=True, help_text='The rule this came from, if it still exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax.taxrule')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['country', 'is_active', 'effective_from'], name='tax_taxrule_country_5c698e_idx'),
        ),
    ]
