# Generated by Django 5.2.6 on 2026-08-31 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_label', models.CharField(blank=True, help_text='Copied at the time, so the record survives the account.', max_length=150)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Changed'), ('delete', 'Deleted'), ('login', 'Signed in'), ('login_failed', 'Failed sign-in'), ('export', 'Exported data'), ('action', 'Performed an action')], db_index=True, max_length=16)),
                ('model_label', models.CharField(blank=True, db_index=True, help_text='e.g. catalog.Product', max_length=100)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_label', models.CharField(blank=True, help_text='What the record was called.', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{"field": {"from": ..., "to": ...}}')),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, help_text='Null once the account is deleted; actor_label keeps the name.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit entry',
                'verbose_name_plural': 'audit log',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['model_label', 'object_id'], name='audit_audit_model_l_b619eb_idx'), models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx')],
            },
        ),
    ]
