# Generated by Django 5.2.6 on 2026-08-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_pg_trgm_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='EAN, UPC or GTIN, as printed on the item.', max_length=64),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='height_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='length_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, help_text="Shipping weight. Falls back to the product's weight.", null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='width_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
