# Generated by Django 5.2.6 on 2026-08-31 06:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='ISO 4217, e.g. INR, USD, GBP', max_length=3, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(help_text='e.g. ₹, $, £', max_length=8)),
                ('symbol_is_prefix', models.BooleanField(default=True, help_text='Shown before the amount rather than after.')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('rounding', models.CharField(choices=[('none', 'Exact (no rounding)'), ('nearest', 'Nearest whole unit'), ('up', 'Always up (charm pricing)')], default='none', max_length=10)),
                ('is_base', models.BooleanField(default=False, help_text='The currency product prices are stored in. Only one.')),
                ('is_active', models.BooleanField(default=True, help_text='Offered to customers in the currency selector.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iso2', models.CharField(help_text='ISO 3166-1 alpha-2, e.g. IN, US, AE', max_length=2, unique=True)),
                ('iso3', models.CharField(blank=True, max_length=3)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('dial_code', models.CharField(blank=True, help_text='e.g. +91', max_length=8)),
                ('is_active', models.BooleanField(default=True, help_text='Selectable in the country selector.')),
                ('shipping_enabled', models.BooleanField(default=True, help_text='Orders may be delivered here.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('currency', models.ForeignKey(help_text='Currency customers in this country see by default.', on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='geo.currency')),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=8, help_text='Units of the quote currency for one unit of the base.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('source', models.CharField(choices=[('automatic', 'Exchange-rate API'), ('manual', 'Set by an administrator')], default='automatic', max_length=10)),
                ('effective_from', models.DateTimeField(db_index=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='geo.currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='geo.currency')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='geo.country')),
            ],
            options={
                'ordering': ['country__name', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['is_active', 'shipping_enabled'], name='geo_country_is_acti_bb81f3_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['base', 'quote', '-effective_from'], name='geo_exchang_base_id_c842aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='geo_state_unique_per_country'),
        ),
    ]
