# Generated by Django 5.2.6 on 2026-08-31 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-effective_from', '-id']},
        ),
    ]
