# Generated by Django 5.2.6 on 2026-08-31 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='Referenced from code, e.g. order_confirmed.', max_length=64)),
                ('language', models.CharField(default='en', help_text='Language code. The default language is the fallback.', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Django template syntax is available, e.g. {{ order.order_number }}.')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, help_text='When this message is sent.', max_length=255)),
            ],
            options={
                'ordering': ['code', 'language'],
                'constraints': [models.UniqueConstraint(fields=('code', 'language'), name='notifications_template_per_language')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('order', 'Order update'), ('payment', 'Payment'), ('shipping', 'Delivery'), ('return', 'Return or refund'), ('stock', 'Back in stock'), ('account', 'Account'), ('promotion', 'Offer')], db_index=True, default='order', max_length=16)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx')],
            },
        ),
    ]
